Set-Location c:\fc3.0\orders

#check for order text file (generated by orderman.rb) and line text file (by brief.rb) , if existed converted it to pdf
Get-ChildItem -Path c:\fc3.0\orders\incoming -Filter *.txt | ForEach-Object {
    $targetFileName = "c:\fc3.0\orders\converted\"+$_.Name
    if ( Test-Path $targetFileName ) {
        Write-Host $targetFileName " already converted, you can open and print it manually to mail it again"
    }Else{
        Start-Process -FilePath $_.FullName -Verb Print -Wait
    }
}
