Set-Location c:\fc3.0\orders

#check for txt file generated by orderman.rb, if existed converted it to pdf
Get-ChildItem -Path c:\fc3.0\orders\incoming -Filter *.txt | ForEach-Object {
    Start-Process -FilePath $_.FullName -Verb Print -Wait
    Move-Item -Force -Path $_.FullName -Destination c:\fc3.0\orders\converted
}

#check for any pdf file, if existed mail to opalus460b
Get-ChildItem -Path c:\fc3.0\orders\incoming -Filter *.pdf | ForEach-Object {
    .\mailsend -smtp smtp.exmail.qq.com -port 465 -ssl -auth -user pcron@foodtrust.cn -pass P123456n  -f pcron@foodtrust.cn -t opalus460b@foodtrust.cn -sub "new pospal order" -M "new order" -attach $_.FullName
    #"C:\FC3.0\orders\incoming\20190322164129-order-E29CA813.pdf"
    Move-Item -Force -Path $_.FullName -Destination C:\fc3.0\orders\mailed
}